FROM khipu/openjdk17-alpine

# work directory 설정
WORKDIR /app

# timezone
ENV TZ="Asia/Seoul"

# spring profile 설정
ARG SPRING_PROFILE

# local -> docker
ARG BUILD_JAR=build/libs/*.jar
COPY ${BUILD_JAR} ./your-project-name.jar

# docker run
ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILE}", "-jar", "./your-project-name.jar"]
